<?php

function _wwm_file_type_displays_view_modes() {
  return array(
    'scale_640x360' => array(
      'title' => t('Scale 640 x 360 (16:9)'),
      'file_types' => array('video', 'image'),
    ),
    'scale_560x315' => array(
      'title' => t('Scale 560 x 315 (16:9)'),
      'file_types' => array('video', 'image'),
    ),
    'scale_480x270' => array(
      'title' => t('Scale 480 x 270 (16:9)'),
      'file_types' => array('video', 'image'),
    ),
    'scale_320x180' => array(
      'title' => t('Scale 320 x 180 (16:9)'),
      'file_types' => array('video', 'image'),
    ),
    'scale_240x135' => array(
      'title' => t('Scale 240 x 135 (16:9)'),
      'file_types' => array('video', 'image'),
    ),

    'scale_640x480' => array(
      'title' => t('Scale 640 x 480 (4:3)'), // Existing
      'file_types' => array('video', 'image'),
    ),
    'scale_480x360' => array(
      'title' => t('Scale 480 x 360 (4:3)'), // Existing
      'file_types' => array('video', 'image'),
    ),
    'scale_360x270' => array(
      'title' => t('Scale 360 x 270 (4:3)'),
      'file_types' => array('video', 'image'),
    ),
    'scale_320x240' => array(
      'title' => t('Scale 320 x 240 (4:3)'), // Existing
      'file_types' => array('video', 'image'),
    ),
    'scale_240x180' => array(
      'title' => t('Scale 240 x 180 (4:3)'),
      'file_types' => array('video', 'image'),
    ),

    'polaroid_landscape' => array(
      'title' => t('Polaroid landscape'),
      'file_types' => array('image'),
    ),
    'polaroid_landscape_rotate_left' => array(
      'title' => t('Polaroid landscape rotated left'),
      'file_types' => array('image'),
    ),
    'polaroid_landscape_rotate_right' => array(
      'title' => t('Polaroid landscape rotated right'),
      'file_types' => array('image'),
    ),
    'polaroid_portrait' => array(
      'title' => t('Polaroid portrait'),
      'file_types' => array('image'),
    ),
    'polaroid_portrait_rotate_left' => array(
      'title' => t('Polaroid portrait rotated left'),
      'file_types' => array('image'),
    ),
    'polaroid_portrait_rotate_right' => array(
      'title' => t('Polaroid portrait rotated right'),
      'file_types' => array('image'),
    ),
    'scale_160x120' => array(
      'title' => t('Scale 160 x 120 (4:3)'),
      'file_types' => array('image'),
    ),
    'scale_160x120_rotate_left' => array(
      'title' => t('Scale 160 x 120 rotated left'),
      'file_types' => array('image'),
    ),
    'scale_160x120_rotate_right' => array(
      'title' => t('Scale 160 x 120 rotated right'),
      'file_types' => array('image'),
    ),
    'scale_320x240_rotate_left' => array(
      'title' => t('Scale 320 x 240 rotated left'),
      'file_types' => array('image'),
    ),
    'scale_320x240_rotate_right' => array(
      'title' => t('Scale 320 x 240 rotated right'),
      'file_types' => array('image'),
    ),
    'scale_480x360_rotate_left' => array(
      'title' => t('Scale 480 x 360 rotated left'),
      'file_types' => array('image'),
    ),
    'scale_480x360_rotate_right' => array(
      'title' => t('Scale 480 x 360 rotated right'),
      'file_types' => array('image'),
    ),
    'scale_640x480_rotate_left' => array(
      'title' => t('Scale 640 x 480 rotated left'),
      'file_types' => array('image'),
    ),
    'scale_640x480_rotate_right' => array(
      'title' => t('Scale 640 x 480 rotated right'),
      'file_types' => array('image'),
    ),
  );
}

/**
 * Implements hook_entity_info_alter().
 */
function wwm_file_type_displays_entity_info_alter(&$entity_info) {
  $view_modes = _wwm_file_type_displays_view_modes();

  foreach ($view_modes as $view_mode_name => $view_mode_info) {
    $entity_info['file']['view modes'] += array(
      $view_mode_name => array(
        'label' => $view_mode_info['title'],
        'custom settings' => FALSE,
      ),
    );
  }


  return $entity_info;
}
